/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-container-high": "#2a2a2a",
        "on-secondary-fixed-variant": "#00468d",
        "on-surface": "#e2e2e2",
        "error": "#ffb4ab",
        "error-container": "#93000a",
        "tertiary-container": "#f6d9ff",
        "on-background": "#e2e2e2",
        "signal-low": "#FF453A",
        "surface-container-highest": "#353535",
        "surface-container": "#1f1f1f",
        "on-error": "#690005",
        "surface-tint": "#c6c6c7",
        "background": "#131313",
        "signal-medium": "#FFD60A",
        "on-primary-fixed-variant": "#454747",
        "inverse-surface": "#e2e2e2",
        "on-primary-container": "#636565",
        "tertiary": "#ffffff",
        "tertiary-fixed": "#f6d9ff",
        "surface-elevated": "#0C0C0C",
        "on-primary": "#2f3131",
        "glass-bg": "rgba(10, 10, 10, 0.7)",
        "on-tertiary-fixed-variant": "#7200a3",
        "on-primary-fixed": "#1a1c1c",
        "surface-container-low": "#1b1b1b",
        "on-secondary-container": "#002957",
        "secondary-fixed": "#d6e3ff",
        "surface-bright": "#393939",
        "surface-dim": "#131313",
        "on-error-container": "#ffdad6",
        "on-secondary-fixed": "#001b3e",
        "secondary-fixed-dim": "#aac7ff",
        "signal-high": "#32D74B",
        "inverse-primary": "#5d5f5f",
        "primary": "#ffffff",
        "primary-container": "#e2e2e2",
        "on-tertiary-container": "#972fca",
        "surface-variant": "#353535",
        "inverse-on-surface": "#303030",
        "on-surface-variant": "#c4c7c8",
        "border-subtle": "rgba(255, 255, 255, 0.08)",
        "primary-fixed-dim": "#c6c6c7",
        "secondary": "#aac7ff",
        "on-secondary": "#003064",
        "outline-variant": "#444748",
        "surface-base": "#000000",
        "primary-fixed": "#e2e2e2",
        "outline": "#8e9192",
        "on-tertiary": "#510074",
        "border-medium": "rgba(255, 255, 255, 0.15)",
        "surface-container-lowest": "#0e0e0e",
        "tertiary-fixed-dim": "#e9b3ff",
        "surface": "#131313",
        "surface-overlay": "#161616",
        "on-tertiary-fixed": "#310048",
        "secondary-container": "#3e90ff",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "container-max": "1440px",
        "unit": "4px",
        "stack-sm": "8px",
        "margin-mobile": "16px",
        "stack-md": "16px",
        "stack-lg": "32px",
        "margin-desktop": "40px",
        "gutter": "24px",
      },
      fontFamily: {
        "label-md": ["JetBrains Mono"],
        "label-sm": ["JetBrains Mono"],
        "stats-number": ["Inter"],
        "headline-md": ["Inter"],
        "display-lg": ["Inter"],
        "body-md": ["Inter"],
        "body-lg": ["Inter"],
        "headline-lg": ["Inter"],
        "headline-lg-mobile": ["Inter"],
      },
      fontSize: {
        "label-md": ["14px", { lineHeight: "20px", letterSpacing: "0.02em", fontWeight: "500" }],
        "label-sm": ["12px", { lineHeight: "16px", letterSpacing: "0.04em", fontWeight: "500" }],
        "stats-number": ["20px", { lineHeight: "24px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "500" }],
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "headline-lg-mobile": ["24px", { lineHeight: "32px", letterSpacing: "-0.01em", fontWeight: "600" }],
      },
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries'),
  ],
}
